name: "Get Jira Issue Key"
description: "Find the Jira Issue Key by commit or PR name"

inputs:
   jira_user:
      description: "Jira username"
      required: true      
   jira_password:
      description: "Jira user password"
      required: true    
   jira_url:
      description: "Jira url"
      required: true
      
outputs:
   jira_key_by_commit:
      description: Jira issue key found on commit message.
      value: ${{ steps.jira-key-by-commit.outputs.issue }}      
   jira_key_by_branch:
      description: Jira issue key found on commit message.
      value: ${{ steps.jira-key-by-branch-name.outputs.issue }}
   
runs:
  using: "composite"
  steps:
    - name: Find Jira issue key in commit messages
      id: jira-key-by-commit
      shell: bash
      run: |
         if [[ "${{ github.event.head_commit.message }}" =~ [a-zA-Z0-9]+-[0-9]+ ]]; then
           keys=$(echo "${{ github.event.head_commit.message }}" | grep -P '[a-zA-Z0-9]+-[0-9]+' -o)
           while IFS='/| ' read -ra KEYS; do
             for issueKey in "${KEYS[@]}"; do
               echo "Run search for: $issueKey"
               curl -D- -u ${{ inputs.jira_user }}:${{ inputs.jira_password }} -H "Content-Type: application/json" "${{ inputs.jira_url }}/rest/api/2/issue/picker?query=$issueKey" -o findjirakey.json             
               key=$(cat findjirakey.json | jq -c '.sections[0].issues[0].key')
               if [ "$key" != null ]; then
                   echo "Jira key found: $key"
                   echo "::set-output name=issue::$key"
                   exit
               fi
             done
           done <<< "$keys"
         fi
         
    - name: Find Jira issue key in branch name
      id: jira-key-by-branch-name
      shell: bash
      run: |
         if [[ "${{ github.ref }}" =~ [a-zA-Z0-9]+-[0-9]+ ]]; then
           keys=$(echo "${{ github.ref }}" | grep -P '[a-zA-Z0-9]+-[0-9]+' -o)
           while IFS='/| ' read -ra KEYS; do
             for issueKey in "${KEYS[@]}"; do
               echo "Run search for: $issueKey"
               curl -D- -u ${{ inputs.jira_user }}:${{ inputs.jira_password }} -H "Content-Type: application/json" "${{ inputs.jira_url }}/rest/api/2/issue/picker?query=$issueKey" -o findjirakey.json             
               key=$(cat findjirakey.json | jq -c '.sections[0].issues[0].key')
               if [ "$key" != null ]; then
                   echo "Jira key found: $key"
                   echo "::set-output name=issue::$key"
                   exit
               fi
             done
           done <<< "$keys"
         fi
